### ISSUE TITLE
Android 12(API 31) not working

### ISSUE THREAD

**Issue by hdytyldrm** [fulvius31/ip-neigh-sdk30#1]
I tried it on samsung s20 android 12 version, it didn't work.

**Comment by fulvius31** [comment]
Could you please be more specific?

I use it for two of my app. For example WeeNet : https://play.google.com/store/apps/details?id=com.sangiorgisrl.wifimanagertool&hl=en_US&gl=US and it works perfect.

**Comment by hdytyldrm** [comment]
> 

Thanks for your answer. To be more specific, when I try this to show devices connecting to hotspot, it works fine for versions before API 30. However, when I try API 30 and later it doesn't work and doesn't show connected devices.

**Comment by fulvius31** [comment]
Try to put `31` as `targetSdk` in `build.gradle` file and test again

**Comment by hdytyldrm** [comment]
I tried the way you described, but unfortunately it didn't work. Only when Mobile data is on, it doesn't show any connected devices. However, log cat shows "socket send success".

**Comment by fulvius31** [comment]
I've tried many times with several devices (also a samsung tablet s8 ultra) : it works.

Try to put your project in github and/or give me more details with logcat.

**Comment by burhanwakhid** [comment]
@fulvius31 
Thank you for great packages. but i have some issue,  I only got 2 ip address which is my device ip and gateway ip, i don't get any other device ip that connect to the same wifi

here's log: 
```
E/ip-neigh( 2437): Message sent
E/ip-neigh( 2437): socket send success
E/ip-neigh( 2437): 192.168.18.1 dev wlan0 lladdr 6c:44:2a:80:81:01 REACHABLE
E/ip-neigh( 2437): 192.168.18.19 dev wlan0 lladdr 82:ef:eb:96:78:f7 STALE
E/ip-neigh( 2437): arp-Finish
E/ArpNDK  ( 2437): getARP: 192.168.18.1 dev wlan0 lladdr 6c:44:2a:80:81:01 REACHABLE
E/ArpNDK  ( 2437): getARP: 192.168.18.19 dev wlan0 lladdr 82:ef:eb:96:78:f7 STALE
```

**Comment by fulvius31** [comment]
If you don't send any ICMP packet (ping) to all the devices connected to your network, you cannot see all of them.

**Comment by burhanwakhid** [comment]
@fulvius31 can you tell me how to send icmp to all device connected with this package?
Thank you

**Comment by fulvius31** [comment]
This package does not allow to send icmp packets. It just read the ARP table.

**Comment by burhanwakhid** [comment]
So, how do i get all devices connected?? 

something like this?
```
for(i = 0; i < 255; i++) {
 // ping to all network
}

String arpTable = ArpNDK.getARP();
```
