### ISSUE TITLE
Android 13 workaround?

### ISSUE THREAD

**Issue by aboozaid** [fulvius31/ip-neigh-sdk30#5]
Hey @fulvius31

Thanks for publishing such a wonderful library. Due to android 13 restrictions do you think a solution of pinging a range of IPs could be a way to go with? I know it would take much time but that what I can see for now

I love to hear from you if you have other solutions for android 13

**Comment by fulvius31** [comment]
Hey @aboozaid , Unfortunately your suggestion does not make sense. Because, sending ICMP packets, it does not mean get ARP table. They are in two different levels in network stack.
