### ISSUE TITLE
What to do for SDK 32?

### ISSUE THREAD

**Issue by xulifan** [fulvius31/ip-neigh-sdk30#6]
Hi, it looks like this code works well for SDK 30 and 31, but not 32. It shows access denied on 32. What can we do for 32?

**Comment by fulvius31** [comment]
Hello, google added a selinux policy for netlink send for getneigh message.

So it's not possible to do that with netlink at least.

**Comment by xulifan** [comment]
Are we able to use AF_ROUTE socket?
